FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY miniapp-notification/target/*.jar app.jar
EXPOSE 8093
ENV JAVA_OPTS="-Xms256m -Xmx768m"
ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS -jar /app/app.jar"]
