# Разрешаем подключения с локального хоста (127.0.0.1 и ::1 для IPv6)
host    all             all             127.0.0.0/8             scram-sha-256
host    all             all             172.16.0.0/12           scram-sha-256
host    all             all             ::1/128                 scram-sha-256

# Разрешаем подключения только с IP-адреса 88.218.169.209
host    all             all             88.218.169.209/32       scram-sha-256

# Запрещаем все остальные подключения (оставляем их на последней строке)
host    all             all             0.0.0.0/0               reject
